"""Shared helpers for the brain's scripts. Stdlib only — no API calls, no SDKs.

The vault contract lives in .claude/agents/. These scripts are provider-neutral:
they must stay runnable by hand, by CI, or by any agent.
"""

import re
from datetime import date
from pathlib import Path

VAULT_ROOT = Path(__file__).resolve().parent.parent
BRAIN = VAULT_ROOT / "brain"

# folder name -> OKF-style `type` for notes in it
FOLDER_TYPES = {
    "projects": "project",
    "areas": "area",
    "resources": "resource",
    "archive": "project",
    "goals": "goal",
    "journal": "journal",
    "people": "person",
    "career": "career-role",
    "meetings": "meeting",
    "decisions": "decision",
    "1on1s": "1on1",
}

# folders that get a generated index.md (superset — missing folders are skipped)
INDEXED_FOLDERS = [
    "projects", "areas", "resources", "goals", "journal", "people",
    "career", "archive", "meetings", "decisions", "1on1s",
]

# never treated as content notes
SKIP_NAMES = {"README.md", "index.md"}
SKIP_FOLDERS = {"inbox", "templates"}

GENERATED_MARKER = "<!-- GENERATED by scripts/regen-indexes — do not edit by hand; rerun the script instead. -->"


def content_notes():
    """Yield (path, top_folder) for every content note in brain/."""
    for top in sorted(BRAIN.iterdir()):
        if not top.is_dir() or top.name in SKIP_FOLDERS:
            continue
        for path in sorted(top.rglob("*.md")):
            if path.name in SKIP_NAMES or "templates" in path.parts:
                continue
            yield path, top.name


def parse_frontmatter(text):
    """Parse a minimal YAML frontmatter subset: scalars and inline lists.

    Returns (dict | None, body_start_offset). None means no frontmatter block.
    """
    if not text.startswith("---\n"):
        return None, 0
    end = text.find("\n---", 4)
    if end == -1:
        return None, 0
    block = text[4:end]
    meta = {}
    for line in block.splitlines():
        m = re.match(r"^([A-Za-z_][\w-]*):\s*(.*)$", line)
        if not m:
            continue
        key, raw = m.group(1), m.group(2).strip()
        if raw.startswith("[") and raw.endswith("]"):
            items = [v.strip().strip("'\"") for v in raw[1:-1].split(",") if v.strip()]
            meta[key] = items
        else:
            meta[key] = raw.strip("'\"")
    body_start = end + len("\n---")
    if text[body_start : body_start + 1] == "\n":
        body_start += 1
    return meta, body_start


def read_note(path):
    text = path.read_text(encoding="utf-8")
    meta, body_start = parse_frontmatter(text)
    return text, meta, body_start


def parse_iso(value):
    """Best-effort YYYY-MM-DD -> date, else None."""
    if not isinstance(value, str):
        return None
    m = re.match(r"^(\d{4})-(\d{2})-(\d{2})", value)
    if not m:
        return None
    try:
        return date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
    except ValueError:
        return None
