"""Shared helpers for the brain's scripts. Stdlib only — no API calls, no SDKs.

The vault contract lives in .claude/agents/. These scripts are provider-neutral:
they must stay runnable by hand, by CI, or by any agent.
"""

import re
from datetime import date
from pathlib import Path

VAULT_ROOT = Path(__file__).resolve().parent.parent
BRAIN = VAULT_ROOT / "brain"
RAW = VAULT_ROOT / "raw"

# top-level brain/<folder> -> OKF-style `type` for notes in it
FOLDER_TYPES = {
    "projects": "project",
    "areas": "area",
    "resources": "resource",
    "archive": "project",
    "meetings": "meeting",
    "decisions": "decision",
    "1on1s": "1on1",
}

# brain/resources/<subfolder> -> note type (personal brain reference material)
RESOURCE_SUBFOLDER_TYPES = {
    "goals": "goal",
    "journal": "journal",
    "people": "person",
    "career": "career-role",
    "vocab": "vocab-entry",
}

# legacy top-level folders (company brain, or pre-0.2.0 personal)
LEGACY_TOPLEVEL_TYPES = {
    "goals": "goal",
    "journal": "journal",
    "people": "person",
    "career": "career-role",
}

RESOURCE_INDEXED_SUBFOLDERS = ["goals", "journal", "people", "career"]
RESOURCE_SUBFOLDERS = set(RESOURCE_SUBFOLDER_TYPES) | {"decisions"}
COMPANY_INDEXED_FOLDERS = ["journal", "people", "meetings", "decisions", "1on1s"]

SKIP_NAMES = {"README.md", "index.md"}
SKIP_FOLDERS = {"templates", "inbox"}

GENERATED_MARKER = "<!-- GENERATED by scripts/regen-indexes — do not edit by hand; rerun the script instead. -->"


def brain_type():
    """personal | company — from .brain-version pin, else infer from layout."""
    pin = VAULT_ROOT / ".brain-version"
    if pin.exists():
        m = re.search(r"^type:\s*(\w+)", pin.read_text(encoding="utf-8"), re.M)
        if m:
            return m.group(1)
    if (RAW / "inbox").is_dir() or (BRAIN / "resources" / "goals").is_dir():
        return "personal"
    return "company"


def inbox_dir():
    """raw/inbox/ for personal brains; brain/inbox/ for company."""
    if brain_type() == "personal":
        return RAW / "inbox"
    return BRAIN / "inbox"


def indexed_folders():
    base = ["projects", "areas", "resources", "archive"]
    if brain_type() == "company":
        return base + COMPANY_INDEXED_FOLDERS
    return base


def resource_subfolder(path):
    try:
        rel = path.relative_to(BRAIN / "resources")
    except ValueError:
        return None
    return rel.parts[0] if rel.parts else None


def note_type(path, top_folder):
    sub = resource_subfolder(path) if top_folder == "resources" else None
    if sub and sub in RESOURCE_SUBFOLDER_TYPES:
        return RESOURCE_SUBFOLDER_TYPES[sub]
    if top_folder in LEGACY_TOPLEVEL_TYPES:
        return LEGACY_TOPLEVEL_TYPES[top_folder]
    return FOLDER_TYPES.get(top_folder)


def is_knowledge_resource(path, meta=None):
    sub = resource_subfolder(path)
    if sub:
        return False
    if meta is None:
        _, meta, _ = read_note(path)
        meta = meta or {}
    return meta.get("type", "resource") == "resource"


def content_notes():
    for top in sorted(BRAIN.iterdir()):
        if not top.is_dir() or top.name in SKIP_FOLDERS:
            continue
        for path in sorted(top.rglob("*.md")):
            if path.name in SKIP_NAMES or "templates" in path.parts:
                continue
            yield path, top.name


def parse_frontmatter(text):
    if not text.startswith("---\n"):
        return None, 0
    end = text.find("\n---", 4)
    if end == -1:
        return None, 0
    block = text[4:end]
    meta = {}
    for line in block.splitlines():
        m = re.match(r"^([A-Za-z_][\w-]*):\s*(.*)$", line)
        if not m:
            continue
        key, raw = m.group(1), m.group(2).strip()
        if raw.startswith("[") and raw.endswith("]"):
            items = [v.strip().strip("'\"") for v in raw[1:-1].split(",") if v.strip()]
            meta[key] = items
        else:
            meta[key] = raw.strip("'\"")
    body_start = end + len("\n---")
    if text[body_start : body_start + 1] == "\n":
        body_start += 1
    return meta, body_start


def read_note(path):
    text = path.read_text(encoding="utf-8")
    meta, body_start = parse_frontmatter(text)
    return text, meta, body_start


def parse_iso(value):
    if not isinstance(value, str):
        return None
    m = re.match(r"^(\d{4})-(\d{2})-(\d{2})", value)
    if not m:
        return None
    try:
        return date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
    except ValueError:
        return None
